server:
  port: 9090
#keySetURI: http://localhost:8080/realms/CAFET/protocol/openid-connect/certs
spring:
  application:
    name: ProjetWebPID2425
  main:
    banner-mode: off
  profiles:
    active:
    - dev
---
spring:
  config:
    activate:
      on-profile:
      - dev
  datasource:
    url: 'jdbc:h2:~/PID_DB/pidDB_2425'
    username: sa
    password:
  sql:
#Permet d'exécuter le fichier data-h2.sql pour insérer des données
    init:
      mode: always
      platform: h2
      encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
#    database-platform: 'org.hibernate.dialect.H2Dialect'
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  http://localhost:8084/realms/CAFET
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          public-key-location: classpath:certificats/keycloak-public-cert.pem

cafet:
  session:
    activate:
      on-time: "0 0 8 * * MON-FRI"
    matin:
      stop-time: "0 30 9 * * 1-5"
    apm:
      stop-time: "0 30 14 * * 1-5"
    soir:
      stop-time: "0 30 19 * * 1-5"
---
spring:
  config:
   activate:
    on-profile:
      - testU
  jpa:
     hibernate:
       ddl-auto: create-drop
  sql:
     init:
       mode: never   
       encoding: UTF-8
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  http://localhost:8084/realms/CAFET
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          public-key-location: classpath:certificats/keycloak-public-cert.pem
cafet:
  session:
    activate:
      on-time: "0 0 8 * * MON-FRI"
    matin:
      stop-time: "0 30 9 * * 1-5"
    apm:
      stop-time: "0 30 14 * * 1-5"
    soir:
      stop-time: "0 30 19 * * 1-5"